# Generated by Django 3.1.3 on 2020-11-26 15:36

from django.db import migrations, models
import releasenotes.models


class Migration(migrations.Migration):

    dependencies = [
        ('releasenotes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='translation',
            name='language',
            field=models.CharField(default=releasenotes.models.get_default_language_code, max_length=7, verbose_name='Language'),
        ),
    ]
